### ISSUE TITLE
As a user I would like to get error message when use the property environments for freestyle step without env vars

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#10]
```yaml
version: '1.0'
steps:
  freestyle_step:
      image: node:latest
      working-directory: ${{initial-clone}}
      environments:
```

Actual result: Rejoice! Your Codefresh YAML is valid!

version of cyv: 0.0.5
