### ISSUE TITLE
The yaml validator skipped the indentation error for commands in freestyle step

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#11]
```yaml
version: '1.0'
steps:
  freestyle_step:
      image: node:latest
      working-directory: ${{initial-clone}}
      commands:
      - test
```

Actual result: Rejoice! Your Codefresh YAML is valid!
version of cyv: 0.0.5
