### ISSUE TITLE
Support the build step's metadata annotations

### ISSUE THREAD

**Issue by noamt** [codefresh-io/cf-yaml-validator#17]
For example
```yaml
metadata:
    set:
      - qa: pending
      - commit_message: ${{CF_COMMIT_MESSAGE}}
      - successful: true
      - quality: 90
      - is_tested: 
          eval: "${{unit_test_step.status}} === success"
```
