### ISSUE TITLE
Incorrect syntax of yml in line "title:sd" wasn't detected by yaml validator

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#2]
I get - Rejoice! Your Codefresh YAML is valid!
```yaml
build_prj:
    type: build
    description: UC - build step
    image-name: codefreshio/yaml-example
    dockerfile: Dockerfile
    tag: ${{CF_BRANCH}}
    title:sd
    when:
     branch:
        only:
          - condition-step
        ignore:
          - condition-step2
```
I should get something like that 
```
can not read a block mapping entry; a multiline key may not be an implicit key at line 11, column 9:                                                         
       when:                                                                                                                                                
           ^
```

```
$ cyv --version
0.0.5
```
