### ISSUE TITLE
Yaml validator can not find error if the blank line is missing between steps

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#3]
```yaml
version: '1.0'
steps:
  freestyle_step:
    image: node:latest
    working-directory: ${{initial-clone}}
    commands:
        - >-
         awerty dfgdfgdfgdf
          sdfsdfsdf
        - npm -v
    when:
      condition:
        all:
          name: "'${{CF_BRANCH}}' == 'condition-step'"
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "skip ci") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'
  composition_step:
      description: Attempting to run as part of composition.
      type: composition
      composition:
        version: '2'
        services:
          app:
            image: 'advance512demo/demochat:master'
            ports:
              - 5000
            depends_on:
              - mongo
          mongo:
            image: mongo
      composition-candidates:
        main:
          image: nhoag/curl
          command: bash -c "sleep 20 && curl http://app:5000/" | echo 'works'
      when:
        condition:
          any:
            noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "skip ci") == false'
            notFeatureBranch: 'match("${{CF_BRANCH}}", "^FB-", true) == false'

```
Result: Rejoice! Your Codefresh YAML is valid!
version of cyv: 0.0.5
