### ISSUE TITLE
When try to use the literal string blocks in one line with - >- I get error message: a line break is expected at

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#4]
```yaml
version: '1.0'
steps:
  freestyle_step:
    image: node:latest
    working-directory: ${{initial-clone}}
    commands:
        - >- awerty dfgdfgdfgdf
          sdfsdfsdf
        - npm -v
```

Result: 
```
Validation error: a line break is expected at line 7, column 14:
            - >- awerty dfgdfgdfgdf
                 ^
```

version of cyv: 0.0.5
