### ISSUE TITLE
Warning: no schema found for step type 'launch-composition'

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#5]
```yaml
version: '1.0'
#comment
steps:
  launch_compose:
    type: launch-composition
    when:
      branch:
        ignore: [ master, other]
    composition:
        version: '2'
        services:
          app:
            image: node:latest
            ports:
              - 3000
```

Result: Warning: no schema found for step type 'launch-composition'. Skipping validation
version of cyv: 0.0.5
