### ISSUE TITLE
if i have error in the line #N - i get the error msg for next line

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#6]
```yaml
//test
version: '1.0'
steps:
  test:
    image: node:latest
```

Result: 
```
Validation error: end of the stream or a document separator is expected at line 2, column 8:
    version: '1.0'
           ^
```

version of cyv: 0.0.5
