### ISSUE TITLE
As a user I would like to see more clear error message when try to use another version of yml

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#7]
```yaml
version: '2.0'
steps:
  build_prj:
      type: build
      description: UC - build step
      image-name: codefreshio/yaml-example
      dockerfile: Dockerfile
      tag: ${{CF_BRANCH}}
```

Actual result: Validation error: Cannot find module '/home/nikolai/.nvm/versions/node/v5.7.1/lib/node_modules/@codefresh-io/yaml-validator/schema/2.0/validator'

Expected result: Unable to find validator for version 2.0
version of cyv: 0.0.5
