### ISSUE TITLE
Incorrect error message when use duplicate properties of yml step

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#8]
```yaml
version: '1.0'
steps:
  test:
    image: node:latest
  build_prj:
      type: build
      description: UC - build step
      image_name: test
      image_name: codefreshio/yaml-example
      dockerfile: Dockerfile
      tag: ${{CF_BRANCH}}
```

Actual result: 
```
Validation error: duplicated mapping key at line 9, column 43:
     ... e_name: codefreshio/yaml-example
                                         ^
```

version of cyv: 0.0.5
