### ISSUE TITLE
Incorrect error message when use duplicate yaml steps

### ISSUE THREAD

**Issue by nCodefresh** [codefresh-io/cf-yaml-validator#9]
```yaml
version: '1.0'
steps:
  build_prj:
    image: node:latest

  build_prj:
      type: build
      description: UC - build step
      image_name: codefreshio/yaml-example
      dockerfile: Dockerfile
      tag: ${{CF_BRANCH}}

  freestyle_step:
      image: node:latest
      working-directory: ${{initial--clone}}
```

Actual result: 
```
Validation error: duplicated mapping key at line 13, column 3:
      freestyle_step:
      ^
```

version of cyv: 0.0.5
